# Python CircleCI 2.0 configuration file

version: 2
jobs:
  build:
    docker:
      # version
      - image: circleci/python:3.6.1
        environment: # environment variables for primary container
          TEST_DB_URL: postgresql://circleci@localhost/circleci_test?sslmode=disable
          FLASK_APP: manage.py
          APP_SETTINGS: testing
          PGHOST: localhost
          PGUSER: circleci
      
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci_test

    working_directory: ~/Flight-Booking-API

    steps:
      - checkout
      # - run: mkdir test-reports
      # Download and cache dependencies
      - restore_cache:
          keys: 
            - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - deps1-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      # run tests
      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            pytest --cov=app/ tests/

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports
      # - store_test_results:
      #     path: test-reports/
      - run:
          name: Run Coverage
          command: |
            . env/bin/activate
            # coverage run -m pytest
            coveralls