version: 2
jobs:
  build:
    docker:
      # version
      - image: circleci/python:3.6.1
        environment: # environment variables for primary container
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: flight_api

    working_directory: ~/Flight-Booking-API

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests
      - run:
          name: Run Tests
          command: |
            . env/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports