"""empty message

Revision ID: bb6d41fee339
Revises: 214af4087427
Create Date: 2019-07-18 14:40:18.373095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6d41fee339'
down_revision = '214af4087427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flights', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'is_admin')
    # ### end Alembic commands ###
